### ISSUE TITLE
Conditional S3 uploading?

### ISSUE THREAD

**Issue by VikiAnn** [imazen/licensing#33]
Do we want to be uploading licenses to S3 every time a subscription webhook is triggered? I'm not sure if it just overwrites the existing license (which is probably ok), but it seems like a potentially unnecessary step if there are no changes.

**Comment by lilith** [comment]
We always want it to update. Safer that way and it's free.

**Comment by VikiAnn** [comment]
OK cool, wasn't entirely sure if that was intentional. Sounds good!
