### ISSUE TITLE
Add support for perpetual licenses

### ISSUE THREAD

**Issue by lilith** [imazen/licensing#9]
ImageResizer subscriptions that are cancelled after 3 years should become Perpetual use licenses for builds released before the cancel date. 

ImageResizer subscriptions purchased with the perpetual add-on, or tagged perpetual should also.

**Comment by VikiAnn** [comment]
@lilith could we chat sometime this week to go over how this should work?

**Comment by lilith** [comment]
Perpetual add-ons have JSON meta data like 

```
{
    "perpetual": true,
    "features": [
        "R_Elite",
        "R_Creative",
        "R_Performance"
    ],
    "allowed_ids": ["enterprise-wide-elite-edition-yearly"]
}
```
or

```
{
    "perpetual": true,
    "features": ["R_Performance"],
    "allowed_ids": ["enterprise-wide-performance-edition-yearly"]
}
```

**Comment by lilith** [comment]
For subscriptions that are in a canceled state, we set two fields: 

`SubscriptionExpirationDate: iso8601 date` 
`Message: Your subscription has expired; please renew to access newer product releases.`

**Comment by lilith** [comment]
You can see the licenses we test the client against here: https://github.com/imazen/resizer/blob/8d258da2b7d700a3320e7e8397e2002956cc5a76/Tests/ImageResizer.Plugins.LicenseVerifier.Tests/LicenseStrings.cs

**Comment by lilith** [comment]
Calculating the start date for the 3-year period is difficult, as `activated_at` is reset whenever the subscription is changed

**Comment by VikiAnn** [comment]
Gah, I meant to reply, not edit your comment!
So for subscriptions with a perpetual add-on, do we just need to remove/not set the `expires` date? Is there anything else we need to do to make them behave like a perpetual license?

> For subscriptions that are in a canceled state, we set two fields:
> 
> `SubscriptionExpirationDate: iso8601 date`
> `Message: Your subscription has expired; please renew to access newer product releases.`

I'm a little confused, is that something that's happening already or is that something I need to add?

> Calculating the start date for the 3-year period is difficult, as `activated_at` is reset whenever the subscription is changed

Could we use the `created_at` from the ChargeBee subscription?

**Comment by lilith** [comment]
Created_at would be okay to use as a stopgap solution. We need to add both fields and remove the expires date.

**Comment by VikiAnn** [comment]
Do regular licenses with a perpetual add-on get `SubscriptionExpirationDate` and the same `Message` too?

**Comment by VikiAnn** [comment]
Oh, looks like we have a `issued` date on licenses, which is derived from the subscription `created_at` for ID licenses and from the subscription `started_at` for regular licenses. Is one of those preferable?

**Comment by lilith** [comment]
Created_at is preferable for determining the 3 years I think.

**Comment by lilith** [comment]
Yes, perpetual licenses of both kinds get the subscriptionexpirationdate
and message.

**Comment by VikiAnn** [comment]
OK, so to recap/make sure I'm doing the right stuff:

Cancelled subscriptions after 3 years are subscriptions with:
- status of "cancelled", and
- created_at 3 years or more in the past

Perpetual licenses are subscriptions with:
- Any add-on that has `perpetual: true` in its meta data

Both kinds should get the `subscription_expiration_date` and `message` fields set on their licenses.

For cancelled subscriptions after 3 years:
`subscription_expiration_date` => subscription `cancelled_at` date (iso8601)
`message` => "Your subscription has expired; please renew to access newer product releases."

For perpetual licenses:
`subscription_expiration_date` => subscription `started_at` date? (iso8601)
`message` => "Your subscription has expired; please renew to access newer product releases."

Do you want a different message for the perpetual add-on licenses? Seems like telling someone who bought a perpetual add-on that their license is expired might be confusing, maybe something like "This license includes the perpetual add-on, and is valid for product releases through [started_at date]"?

**Comment by lilith** [comment]
Subscriptionexpirationdate and message should only be set if the subscription is canceled. The assumption is that perpetual licenses are usually canceled by the end of the first year, but we wait until then to display the message.

**Comment by lilith** [comment]
We don't care which event triggers the update as long as the update happens on time.

**Comment by lilith** [comment]
I agree the message should also reflect that it is valid for releases prior to [date]

**Comment by VikiAnn** [comment]
Ohhh ok. So perpetual licenses would be more like:

1. Subscription with perpetual add-on purchased
2. Subscription created webhook hits our endpoint
3. We generate the license as usual, except that the `expires` is lifted
4. Usual behavior for any other endpoints until cancellation
5. Subscription cancellation webhook (or whatever webhook with that subscription) hits our endpoint
6. We update the license with the `subscription_expiration_date` and `message` fields
